name: LustUpdate Auto Commit

permissions:
  contents: write

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-lustupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update LustUpdate file
        run: |
          date '+%Y-%m-%d %H:%M:%S' > LustUpdate

      - name: Commit and push changes
        run: |
          git add LustUpdate
          git commit -m "[bot] Update LustUpdate file" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
